version: '3'

services:

  mariadb:
    image: mariadb:10.8.2
    container_name: well4u_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=well4u_db
      - MYSQL_DATABASE=well4u_db
      - MYSQL_PASSWORD=well4u_db
    ports:
      - 9814:3306
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: well4u_phpmyadmin
    environment:
      - PMA_HOST=well4u_db
      - UPLOAD_LIMIT=5242880000
    ports:
      - 9815:80
volumes:
  mariadb_data:
